FROM node:18

WORKDIR /usr/src/app

COPY pnpm-lock.yaml ./
COPY package.json ./

RUN npm install -g pnpm
RUN pnpm install

COPY . .

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "start:prod"]
