# 베이스 이미지 설정
FROM node:18

# 작업 디렉토리 설정
WORKDIR /usr/src/app

# 종속성 파일 복사 및 설치
COPY pnpm-lock.yaml ./
COPY package.json ./
RUN npm install -g pnpm
RUN pnpm install
RUN npm install pm2 -g

# 애플리케이션 소스 복사
COPY . .
COPY docker-compose.yml .

# 애플리케이션 빌드
RUN pnpm build

# 포트 노출
EXPOSE 3000

# 애플리케이션 실행
CMD ["pm2-runtime", "start", "dist/main.js"]

