FROM node:18

WORKDIR /usr/src/app

COPY pnpm-lock.yaml ./
COPY package.json ./

RUN npm install -g pnpm
RUN pnpm install
RUN npm install pm2 -g

COPY . .

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start:prod"]
